version: '3'
services:
  sippuas:
    image: sipp
    container_name: sippuas
    restart: always
    expose:
      - 3060
    ports:
      - "3060:3060/udp"
    command: -p 3060 -sn uas

  sippuac:
    image: sipp
    container_name: sippuac
    depends_on:
      - sippuas
    restart: always
    expose:
      - 3062
    ports:
      - "3062:3062/udp"
    command: -p 3062 -sn uac sippuas:3060
